### ISSUE TITLE
Any news about 1.21 port?

### ISSUE THREAD

**Issue by vac2003** [Encrypted-Thoughts/DimensionPortalLinker#4]
Hello,
I used your mod on my server and I loved it! I was wondering if there's any intention to update it to 1.21 since I want to update my server to 1.21 and currently the 1.20.6 jar file does not work on a 1.21 fabric server.

Best wishes,
Buer

**Comment by Encrypted-Thoughts** [comment]
Think I've updated it to 1.21. It required changing a lot because of all the changes to how portals work in 1.21.
Let me know if you have any issues with it.

https://github.com/Encrypted-Thoughts/DimensionPortalLinker/releases/tag/1.1.3

**Comment by vac2003** [comment]
It works! Thank you so much for your effort!

**Comment by vac2003** [comment]
Only problem I found is that when i go through the custom dimension end portal instead of going back to the custom overworld dimension i get tp-ed back to the default overworld.

**Comment by vac2003** [comment]
I made a datapack that adds a an overworld dimension and an end dimensions.
When I go through the portal in the end dimension instead of tp-ing at the custom overworld dimension i get tp-ed to the default overworld. 
Not sure if it's a mod issue or datapack issue.

**Comment by Encrypted-Thoughts** [comment]
Yeah that's because the portal from the end to the overworld doesn't teleport the player to the overworld exactly, it teleports them to their spawn point or the world spawn point if they haven't set their spawn anywhere.

I could probably hijack that and make it teleport entities to the same spot as the world spawn coordinates in the dimension specified but that comes with the issue of that point potentially not being valid in the custom dimension... so I'd really need to add a config option to define spawn per dimension for that to work. Might not be a terrible idea.

I guess the datapack solution would be to change the players spawn point to where you want it to be in the custom dimension when they go through the portal. Probably by changing it when they near the portal in some range instead of immediately on entering the custom end dimension so their beds/respawn anchors still work if they die. You'd still have the problem of entities other than the player going to the wrong dimension though... Might be easier to just set up a spot that teleports players when they enter it instead of using the portals.

**Comment by vac2003** [comment]
I understand, thank you so much for the information!

**Comment by Encrypted-Thoughts** [comment]
Added the ability to override world and player spawns per dimension as well as commands for editing the config.
https://github.com/Encrypted-Thoughts/DimensionPortalLinker/releases/tag/1.1.4

**Comment by vac2003** [comment]
You absolute madlad, I just tested it and it works perfectly, thank you so much!
